In [ ]:
import pandas as pd

In [ ]:
import warnings
warnings.filterwarnings(action='ignore')

In [ ]:
train_df = pd.read_csv('/content/ratings_train.txt', encoding='utf8', sep='\t')

결측치 처리

In [ ]:
train_df=train_df[train_df['document'].notnull()]

한글 정규화시키기

In [ ]:
import re
train_df['document'] = train_df['document'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))

In [ ]:
test_df=pd.read_csv('/content/ratings_test.txt',encoding='utf8',sep='\t')

In [ ]:
test_df=test_df[test_df['document'].notnull()]

In [ ]:
test_df['document'] = test_df['document'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))

한글을 토큰화 하기위한 라이브러리 설치

In [ ]:
#pip install konlpy

  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from konlpy.tag import Okt
okt = Okt()

토큰화

In [ ]:
tfidf = TfidfVectorizer(tokenizer= okt.morphs , ngram_range=(1, 2), min_df = 3, max_df = 0.9)

토큰화 시킨것 피트시키고 트렌스폼시키기

In [ ]:
tfidf.fit(train_df['document'])
train_tfidf =tfidf.transform(train_df['document'])
train_tfidf

<149995x115612 sparse matrix of type '<class 'numpy.float64'>'
	with 2703859 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf.inverse_transform(train_tfidf)

In [ ]:
test_tfidf = tfidf.transform(test_df['document'])

로지스틱회귀를 통해 정확도 측정

In [ ]:
lr = LogisticRegression(random_state = 0)

In [ ]:
lr.fit(train_tfidf, train_df['label'])

LogisticRegression(random_state=0)

In [ ]:
test_predict = lr.predict(test_tfidf)

In [ ]:
print('감성 분석 정확도 : ', round(accuracy_score(test_df['label'], test_predict), 3))

감성 분석 정확도 :  0.852


크롤링한 네이버 뉴스기사를 긍정 부정 판단 긍정 = 1 , 부정 = 0

In [ ]:
news=pd.read_csv('/content/네이버뉴스_서울_창업_20200101_20200131.csv',encoding='utf8')

In [ ]:
news['title'] = news['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title=''
for i in range(len(news.title)):
  news_title=news_title + news.iloc[i,2]+''

print(news_title)

오전 서울 서초구 AI 양재허브에서 열린 창업 활성화를 위한 청년과 대화에서 참석자들과 기념촬영을 하고... 책임지는 서울, 폐업·실직·빈곤의 두려움 없는 서울, 청년의 꿈을 이루는 서울, 고르게 발전하는 서울...서울시가 뇌병변장애인비전센터를 설치하고, 장애인활동지원 등을 담당하는 '종합재가센터'도 9개소를... 위기가구 발굴을 위해서 올해부터는 공동주택 관리비 혹은 건강보험료 3개월 이상 체납, 휴·폐업 사업자...사회서비스원 직접 운영 국공립어린이집 개소 서울형 긴급복지, 기초보장 문턱 낮춰 어르신·중장년 인생... 위기 가구 발굴대상에 공동주택 관리비 체납, 휴·폐업 사업자, 세대주가 사망한 가구의 경우를 추가한다. 50...전국에서 쉐어하우스(공유주택)이 가장 많은 자치구는 서울 마포구로 나타났다. 강남구와 관악구가 뒤를... 중심으로 폐업이 일어나고 있다는 뜻”이라며 “창업시 꼼꼼한 준비가 필요하다”고 강조했다. 이...사업화에 성공하더라도 초기 자금이 바닥나 창업 3~4년 만에 폐업하는 스타트업도 부지기수다. 한국에서 유니콘(unicorn·기업 가치가 1조 원을 넘는 스타트업)이 좀체 탄생하지 못하는 데는 이와 같은 사정이 있다. 서울시...찍고 서울로 간다는 말이 있다. 이는 통신사 자료에서도 나타난다"고 했다. 이어 "20대 초반은 교육 때문에... '스타트업'(창업)과 관련해, 김 지사는 "100억 넘는 투자를 한 스타트업이 전국에서 2017년 20개, 2018년 63개, 2019년...박 장관이 기존 정치경력에 더해 중기부에서 행정능력을 입증하면 다음 서울시장 선거에서 유리한 입지를... 완화했다"며 "폐업을 하고 있는 사람까지 포함해 창업을 할 수 있게 하고 수혜 연령도 39세 이하에서...그는 "창업과 폐업이 스펙이라면 활용할 가치가 있어야 하는데 활용할 곳이 없다"며 "스펙이라는 것은 취업... 김성환 당대표비서실장은 이날 임오경 전 서울시청 여자핸드볼팀 감독을 발탁한 인재영입 15호 발표식 뒤...전 서울시청 여자핸드볼팀 감독을 영입

In [ ]:
news_title_tfidf = tfidf.transform([news_title])
news_title_predict = lr.predict(news_title_tfidf)
news_title_predict

array([1])

In [ ]:
news2=pd.read_csv('/content/네이버뉴스_서울_창업_20200201_20200228.csv',encoding='utf8')

In [ ]:
news2['title'] = news2['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title2=''
for i in range(len(news2.title)):
  news_title2=news_title2 + news2.iloc[i,2]+''

print(news_title2)

단, 폐업 경험이 있을 경우 과거와 다른 업종의 제품·서비스를 가지고 창업해야 지원받을 수 있다. 서울창조경제혁신센터와 각 대학은 창업 아이템 개발 동기, 사업화 전략, 시장 진입과 성과창출 전략, 대표자와...그런데 저는 지역에 내려와 창업하고 결혼도 했네요. 도시생활에서 조금만 눈을 돌리면 다른 삶의 기회가 있다는 것을 청년들이 알면 좋겠어요". 서울 출신 이상혁 대표(35, 속초 소호 259 게스트하우스 운영)는 5년 전...사업’에 서울지역 운영 주관기관으로 연속 선정되었다고 19일 밝혔다. 재도전 성공패키지 지원 사업은 폐업이력이 있는 (예비)재창업자들을 대상으로 하는 사업화 안정을 위한 다양한 패키지 형태의 창업지원 사업이다....박주현 민주평화당 최고위원은 "서울의 역사문화의 중심이라고 할 수 있는 청계천에서 소상공인의 생태가 통째로 무너지는 모습이 너무나 안타깝다"면서 "정부는 창업과 도심재생을 위해 많은 예산을 투자하고 있지만...1957년 4월15일 서울에서 태어났다. 경기고등학교와 성균관대학교 법학과를 졸업한 뒤 같은 대학교... 공공조달제도를 21년 만에 전면 개편하고 폐업한 기업이 같은 업종으로 다시 창업하면 정부가 지원하는 제도 등도...휴·폐업부지는 첨단산업과 창업지원시설, 문화·레저, 행복주택 등으로 고밀·복합 개발하고 도심 내 방치된 공업지역은 공기업이 주도하여 복합개발을 추진한다. 문 대통령은 국토부의 올해 업무계획에 대해 “서울과...9) * ( ) : 전년 대비 증가율(%) 지역별로는 서울(9.1%↓), 경기(4.7%↓), 전북(9.0%↓) 등에서 감소했다.... 합병·분할, 폐업 후 동일업종 재개 등 포함 ㅇ 기술기반창업 : 기술기반업종을 영위하는 기업의...경기불황으로 자영업 폐업이 속출하는 가운데서도 프랜차이즈 가맹점 창업으로 내몰리는 사람들 수는... 지역별로 보면 가맹점은 경기(6만4020개)에 가장 많았으며, 서울(4만7049개), 경남(1만7857개) 순으로...국토부는 휴·폐업부지를 △첨단산업 △창업지원시설 △

In [ ]:
news_title_tfidf2 = tfidf.transform([news_title2])
news_title_predict2 = lr.predict(news_title_tfidf2)
news_title_predict2

array([1])

In [ ]:
news3=pd.read_csv('/content/네이버뉴스_서울_창업_20200301_20200331.csv',encoding='utf8')

In [ ]:
news3['title'] = news3['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title3=''
for i in range(len(news3.title)):
  news_title3=news_title3 + news3.iloc[i,2]+''

print(news_title3)

서울시가 예비창업자들이 프랜차이즈 가맹점 창업시 필수적으로 확인해야 하는 '가맹본부 정보공개서'에... 의뢰하고 폐업한 업체는 시가 직접 등록취소를 진행한다. 시는 서울 소재 803개 프랜차이즈 본부의...지원으로 폐업 위기에 몰린 소상공입을 돕고, 막힌 소비심리에 '숨통'을 틔우기 위한 지원에 나선다. 서울... 대상은 관광사업, 도소매업, 숙박·음식점 등과 함께 전반적인 경기침체로 어려움을 겪고 있는 기술창업기...3대 방향은 폐업위기에 직면한 영세소상공인 및 중소기업에 대한 경제적 지원, 얼어붙은 소비심리 회복을 위한 소비자의 구매촉진 유도, 정부의 코로나19추경을 서울시 맞춤형으로 재설계한 피해업종별 지원이다. 이번...주요 협력과제는 △시민 라이프 스타일 및 소비 트렌드 변화 트래킹 △소지역 기반 융합 인덱스 제공 △우리마을가게 상권분석 배후지 정보 개발 △서울시 소상공인 창업 및 폐업 지도 및 데이터 △지역별 소비특성...현재 푸드트럭 점주들이 매출을 올릴 수 있는 곳은 서울시가 운영하는 ‘밤도깨비 야시장’ 등과 같은... 어렵게 마련한 돈으로 소자본 창업했는데 정작 제도가 현실을 따라오지 못해 폐업률이 속출하고 있다”며...중고 주방기기 처분업체가 모여 있는 서울 황학동 주방거리. 이곳에 있는 폐업 지원업체 H사는 때아닌... 폐업과 창업이 톱니바퀴처럼 맞물려 돌아가는 국내 자영업 생태계의 선순환 구조가 깨졌다는 지적이 나온다....◆ 학력 1980년 서울 보성고등학교를 졸업했다. 고려대 전기공학과를 졸업했다. 미국 시라큐스대학교에서 전자계산학 석사학위를 받았다. ◆ 가족관계 허만정 GS그룹 창업주가 할아버지고 허 창업주의 넷째아들인...직접대출'과 서울시의 저신용 영세 소상공인 대상의 '대환대출' 정책, 그리고 최근 쏟아지는 지자체별 '재난... 필자의 딸이 알바로 일했던 대형 뷔페는 이번 사태가 터지자 폐업을 결정했다(관련 기사 : 코로나19 확진자...그 결과 부산시는 현재 35개의 산업단지와 조성계획까지를 포함하면 40개의 산업입지를 확보함

In [ ]:
news_title_tfidf3 = tfidf.transform([news_title3])
news_title_predict3 = lr.predict(news_title_tfidf3)
news_title_predict3

array([1])

In [ ]:
news4=pd.read_csv('/content/네이버뉴스_서울_창업_20200401_20200430.csv',encoding='utf8')

In [ ]:
news4['title'] = news4['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title4=''
for i in range(len(news4.title)):
  news_title4=news_title4 + news4.iloc[i,2]+''

print(news_title4)

전망된다"며 "창업에 드는 초기 투자비용을 회수하지 못하고 폐업하는 자영업자가 늘면 가계부채 증가, 파산 등이 사회적 문제로 불거질 가능성이 있다"고 지적했다. 지난 10여 년간의 통계를 봐도 서울에서...마포구 연남동은 지난 몇 년 사이 서울에서 젠트리피케이션이 가장 빠르게 진행된 지역 중 하나다. 여러... 자영업자들의 전체 매출액은 늘어나지만 평균 영업기간은 줄어들고, 창업과 폐업 수도 급증한다. 높아진...고인석 서울기술연구원장은 “최근 코로나19 위기에 따라 경기가 침체되고, 소비심리가 위축돼 휴·폐업 문제가 도시문제로 대두되고 있다”며 “본 협약은 경기침체를 해결하는 하나의 방안으로, 서울 청년창업과...생존기간이 짧은 단점이 있다"며 "휴게음식점 창업을 염두에 두고 있다면 사전에 업무교육을 받는 한편 기회비용을 철저히 따져봐야 한다"고 말했다. 서울 휴게음식점 폐업률 연간 추이(단위: %) [자료=부동산114]창업한지 48년, 지금의 버스로 옮긴 지 35년만이었다. 스낵카는 대형버스를 개조해 만든 이동식 식당이다.... 박씨는 "지난해 미래유산이라고 보수유지비를 지원해준다던 서울시가 막상 폐업 후 기증한다고 하니까...2015년 창업한 이후 처음 겪는 상황에 김 대표는 적잖이 당황한 모습이었다. 3월까지는 어떻게든 버텨왔다는... 지원금을 서울시에 등록된 모든 여행사에 줄 수 있는 상황이 아니다”라며 “당장 폐업할 곳에 지원하는...희망폐업 시행 등을 요구하는 'CU 피해사례 보고' 기자회견을 열었다. 전국가맹점주협의회는 "점주는... 보광창업투자 회장과 홍석규 보광그룹 회장이 남동생이다. ◆ 상훈 서울지방검찰청에 근무하던 2000년 12월28일...관악 창업벤처밸리 조성으로 일자리 창출 및 지역경제 활성화 △신림 상권 르네상스 사업 성공 등 3대 핵심공약과 비전을 제시한 것도 이 때문이다. 지역 내 도시재생사업, 재개발재건축 사업도 해결해야 한다. Q. 서울...◇코로나19에 꺾인 개인회생…회생 취하 청구 인용 50대 가장인 김씨가 서울회생법원의

In [ ]:
news_title_tfidf4 = tfidf.transform([news_title4])
news_title_predict4 = lr.predict(news_title_tfidf4)
news_title_predict4

array([1])

In [ ]:
news5=pd.read_csv('/content/네이버뉴스_서울_창업_20200501_20200531.csv',encoding='utf8')

In [ ]:
news5['title'] = news5['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title5=''
for i in range(len(news5.title)):
  news_title5=news_title5 + news5.iloc[i,2]+''

print(news_title5)

시는 폐업을 준비하고 있는 소상공인·자영업자들에게 재창업을 위한 컨설팅, 일자리 알선 등에 나선다. 26일 서울시에 따르면 시는 신종 코로나바이러스 감염증(코로나19)으로 지난해부터 추진하고 있는 '폐업...또한 공단 주관 창업･재기 교육과정과 서울국세청 주관 납세자세법교실에 상대 기관의 교육내용(창업자･폐업자를 위한 세법교육･세무안내, 소상공인･전통시장 상인에 대한 창업･재기 지원정책안내)을 추가해...1 이전 창업자) ▼ 신청일 기준 실제 영업중인 소상공인- 현재 휴·폐업 중이거나 사실상 폐업 상태에 있는 업체 지원 제외- 종사자수(5인미만, 제조업·광업·건설업·운수업 10인 미만) 기준 준수 서울시 온라인 신청시...이전 창업자), 지급 신청일 기준 실제 영업중인 소상공인(현재 휴·폐업 중이거나 사실상 폐업상태에 있는... 어려워 폐업한 경우 지원되나요? "서울시 자영업자 생존자금은 공고일 기준 서울시에 사업장을 두고 실제.../ 서울시 서울시가 신종 코로나바이러스 감염증(코로나19) 사태로 폐업 위기에 몰린 소상공인을 지원하는... 가게 문을 연 지 반년이 채 안 된 자영업자들은 초기 창업자들의 피해가 더 크다며 시에 현금 지원을 요구했다....서울시 코로나19로 경제적 타격을 입게된 자영업자와 소상공인을 대상으로 생존자금을 지원하는 서울시... 1 이전 창업자) ▼ 신청일 기준 실제 영업중인 소상공인- 현재 휴·폐업 중이거나 사실상 폐업 상태에 있는...사업자등록증상 사업장 소재지가 서울인 2919년 9월 1일 이전 창업자 중 지난해 연 매출이 2억 미만인... 소재지가 서울인 종사자 5인 미만의 사업장인 경우 지원 가능하면, 신청일 기준으로 휴업이나 폐업 중인...서울 용산구(구청장 성장현)가 코로나19로 인해 피해를 입은 자영업자 생존자금을 지원한다고 밝혔다. 지역경제 활성화에 기여하기 위해서다. 지원대상은 2019년 9월 1일 이전 창업자 중 지난해 연매출이 2억 원...이 때문에 서울 휴게음식점 폐업률은 올해 70%에 육박할 전망이다. 이런 가

In [ ]:
news_title_tfidf5 = tfidf.transform([news_title5])
news_title_predict5 = lr.predict(news_title_tfidf5)
news_title_predict5

array([1])

In [ ]:
news6=pd.read_csv('/content/네이버뉴스_서울_창업_20200601_20200630.csv',encoding='utf8')

In [ ]:
news6['title'] = news6['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title6=''
for i in range(len(news6.title)):
  news_title6=news_title6 + news6.iloc[i,2]+''

print(news_title6)

서울에 문을 여는 프랜차이즈 브랜드 5개 중 1개는 3년 안에 폐업하는 것으로 나타났다. 평균 창업비용은 감소세를 이어가 지난해 1억3,200만원 수준이었다. 서울시는 18일 발표한 ‘2019년 서울 프랜차이즈...지나면 폐업하는 것으로 나타났다. 서울시가 18일 발표한 '2019년 프랜차이즈 분석결과'에 따르면... 가맹점 평균 창업비용은 1억3천242만원으로 조사됐다. 이 중 가맹비는 1천137만원, 보증금 480만원, 교육비...━ ◆ 도소매업 생존율 높고 외식업은 3년 후 10곳 중 2곳 이상 폐업 ━ 브랜드의 생존율을 살펴보면... 활용하여 서울시 프랜차이즈 사업 현황을 파악하게 되었다”며 “프랜차이즈 창업을 고민하는 시민들에...소재지가 서울이어야 한다. 대표자 주소지와는 관계없다. 2019년도 9월 1일 이전 창업자로 2020년 2월 29일... 지급 신청일 기준, 실제 영업 중인 소상공인으로 사실상 폐업상태에 있는 업체는 지원 대상에서 제외된다....외식업 브랜드는 창업 후 3년이 지나면 10곳 중 2곳 이상 폐업하는 것으로 나타났다. 서울시 등록 브랜드 10개 중 3개꼴로 가맹본부가 구입한 가격과 가맹점주에 공급하는 상품, 재료 등의 가격 차액이 발생하는...이의신청해 △사망진단서 △가족관계증명서 △폐업사실증명서를 제출해야 한다. 자치구 이의신청심의위원회에서 적격 판정 받으면 자금을 받을 수 있다. 예산 한계 때문에 신규 창업자는 지원하지 못한다는 설명이다....서울 넥스트로컬은 지역연계형 청년창업 지원 사업이다. 서울 거주 청년(만 19∼39세)을 대상으로 두 달간 8개... 고향인 충남 금산군의 오랜 양조장이 폐업 위기에 놓여 있다는 얘기를 듣고, 할아버지 생전의 단골집을...관련 제조사업의 폐업을 결정한 것이다. 1978년 서울 구로구에서 창업한 지 40여년 만이다. 한때 연매출 700억원을 넘겼고 2018년에는 최우수협력사로도 선정된 우량회사였다. 2016년에는 대기업의 자동차부품 사업 확대로...이스타항공은 29일 서울 강서구 본사에서

In [ ]:
news_title_tfidf6 = tfidf.transform([news_title6])
news_title_predict6 = lr.predict(news_title_tfidf6)
news_title_predict6

array([1])

In [ ]:
news7=pd.read_csv('/content/네이버뉴스_서울_창업_20200701_20200731.csv',encoding='utf8')

In [ ]:
news7['title'] = news7['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title7=''
for i in range(len(news7.title)):
  news_title7=news_title7 + news7.iloc[i,2]+''

print(news_title7)

최근 코로나19로 숙박업에 타격을 입어 폐업 상태입니다. 종로청년창업센터에 입주한 게릴라하우스에서는... 좌석당 월 4만 원의 자기부담금을 제외하고 컨설팅 등 각종 지원이 무료로 제공됩니다. 서울뉴스 이재원입니다.자치구 차원에서 관내 소상공인 지원자금을 푼 것은 서울에서는 이번이 처음이다. 이번 조치로 창업시기나... 사실상 폐업상태인 업체나 유흥업소, 도박·향락·투기 등 불건전 업종은 지원대상에서 제외된다. 서울형...지원 대상은 2019년 3월 1일 이전 창업한 서울 소재 4인 이하 디자인 기업 또는 개인 디자이너다. 폐업했거나 사실상 폐업 상태인 기업은 제외한다. 자세한 사항은 서울디자인재단 홈페이지(www.seouldesign.or.kr) 등을...이전에 창업한 4인 이하 디자인 기업이나 개인 디자이너다. 단, 현재 폐업 중이거나 사실상 폐업 상태에 있는 기업은 제외된다. 한국디자인진흥원에 따르면 지난해 기준 디자인 전문기업 5570개 중 58.7%인 3270개가 서울...서울시는 코로나19로 인한 실직·폐업 등으로 어려움을 겪고 있는 서울 거주 구직자를 대상으로 경북 상주... 서울시가 농림축산식품부와 협업해 개설한 이 과정은 농촌일자리 현황, 취·창업 정보를 얻고, 선도농가...지원기간 중 폐업하거나 서울 밖으로 주소지가 변경될 경우에도 지원이 종료된다. 창업가 주거지원 사업에 대해 궁금한 창업가 또는 추천기관은 인베스트서울센터 또는 서울시 투자창업과로 문의하면 된다. 김의승...코로나19로 휴·폐업, 실직 등으로 위기 상황에 놓인 자영업자, 무급휴직자, 프리랜서 등이 그 대상이다.... 7월에는 '디자인 분야' 창업을 꿈꾸는 청년들을 지원하기 위한 서울디자인창업센터가 홍대입구역 복합역사...서울시는 코로나19로 인한 실직·폐업 등으로 어려움을 겪고 있는 서울 거주 구직자를 대상으로 상주... 서울시가 농림축산식품부와 협업해 개설한 농촌일자리 탐색교육과정은 농촌일자리 현황, 취·창업 정보를 얻고...서울시여성가족재단은 여성·가족의 일과 삶의 균형을 

In [ ]:
news_title_tfidf7 = tfidf.transform([news_title7])
news_title_predict7 = lr.predict(news_title_tfidf7)
news_title_predict7

array([1])

In [ ]:
news8=pd.read_csv('/content/네이버뉴스_서울_창업_20200801_20200831.csv',encoding='utf8')

In [ ]:
news8['title'] = news8['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title8=''
for i in range(len(news8.title)):
  news_title8=news_title8 + news8.iloc[i,2]+''

print(news_title8)

서울 영등포구는 신종 코로나바이러스 감염증(코로나19) 사태로 실직·폐업한 취약계층에 공공일자리... 구는 일자리 제공에 더해 요양보호사 양성, 집수리 교육, 치매관리사 양성, 신임 경비 교육, 창업형 유튜버 교육 등...실직·폐업 등의 피해를 입은 사람이다. 신청은 26일까지 강서구청 일자리정책과로 제출하면 된다. 동대문... 경제지원센터’ 창업자들로 구성된 DDM 메이커 협동조합이 서울시 예비마을기업으로 선정됐다고 24일 밝혔다....이에 서울시는 18일 농촌 지역의 일손부족을 해결하고, 실직·폐업 등으로 일자리를 찾는 서울시민 100명을... 선발 기준에 명시된 교육은 서울시에서 운영하는 농업 분야 취·창업 전직 희망자 및 영농 관련...서울 영등포구가 코로나19로 생계에 어려움을 겪는 지역 주민들을 위해 희망일자리 사업을 확대 추진한다고 22일 밝혔다. 희망일자리 사업은 코로나19로 인해 실직·폐업한 취업 취약계층에게는 일자리를 제공해 생계...이제 맛과 영양 두 마리의 토끼를 잡은 식단으로 주방을 폐업시켜 드리겠습니다. 한편, 'MIK HOT SPOT(메이드인코리아 온라인전시회)' 참가 기업을 지원한 '서울 먹거리 창업센터'는 농식품 관련 기업들의 혁신적인...서울시여성가족재단은 여성·가족의 일과 삶의 균형을 지원하는 복합문화공간이자 여성들의 일자리를... 있는 폐업 1년 미만의 여성 재창업자라면 지원이 가능하다. 선정된 기업·재창업자는 유형별 맞춤형 전용 공간 및...30일 국토교통부는 전북 전주시와 서울 서대문구, 경기 동두천시, 인천 동구, 경남 사천시 등 총 5곳에 '빈집 특화재생 시범사업' 대상지를 선정했다고 밝혔다. 전주 지역은 공공임대주택과 예술인 창업시설‧건강지원센터...부동산업 제외하면 전년 상반기 대비 0.1% 증가 폐업 기업 수는 깜깜이...경기 상황 파악 어려워 자생적 창업인지 정부 지원 창업인지도 중요 신보훈 기자 bbang@ajunews.com 서울 강남구 코엑스에서 열린 '제57회 프랜차이즈...국내 창업기업의 절반 이상이 

In [ ]:
news_title_tfidf8 = tfidf.transform([news_title8])
news_title_predict8 = lr.predict(news_title_tfidf8)
news_title_predict8

array([1])

In [ ]:
news9=pd.read_csv('/content/네이버뉴스_서울_창업_20200901_20200930.csv',encoding='utf8')

In [ ]:
news9['title'] = news9['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title9=''
for i in range(len(news9.title)):
  news_title9=news_title9 + news9.iloc[i,2]+''

print(news_title9)

매년 1000개 이상 사업체가 폐업과 창업을 반복해 소통을 위한 접점을 찾기 어려웠다. 혼잡한 교통과 부족한 편의시설은 우수 인력의 이탈 우려를 높였다. 산단공 서울지역본부는 지난 2010년부터 구조 고도화...올해 서울에서 폐업한 유·무료 직업소개소는 175곳이다. 일을 중단한 자영업자, 그로 인해 일터를 잃은... 이달 초 폐업한 뒤 셈을 해보니 보증금 3500만원은 미납한 월세로 사라졌다. 권리금은 커녕 창업할 때...임차해 창업했고 지급일 기준까지 실제 영업중인 소상공인이다. 사실상 휴·폐업 중인 업체나 유흥·사행·도박 등 중소기업육성기금 융자지원 제한 업종과 서울시 자영업자 생존자금 수혜자는 제외된다. 신청을...서울 성북은 고려대학교 캠퍼스와 연계해 창업생태계를 구축하고 정주 여건을 개선한다. 약 17만1000㎡ 땅에... 이들 지역에선 폐업 건물이나 이전 예정 부지 등에 복합문화공간을 조성한다는 방침이다. ▲ 국토부 제공...스타벅스커피 코리아가 카페 창업으로 쓴 맛을 맛 본 중장년층의 재기를 지원한다. 스타벅스커피 코리아는... 제주도에서 커피숍을 운영하다 경영 악화로 폐업을 하고 서울로 다시 상경했다는 한 지원자는 새로운 도전을...◀ 앵커 ▶ 집을 사려는 사람보다 팔려는 사람들이 많아지면서, 서울의 매수우위 지수가 3개월 만에 100... 또 사회적 거리두기 2단계가 시작된 지난달 16일을 지원 기준일로 정하면서 그전에 폐업하거나 그 후에 창업한...서울관광재단(대표 이재성)은 서대문구와 함께 가을을 맞아 도심 감성여행으로 신촌과 홍제천 일대를... 독수리다방은 2005년 폐업했다가 8년 만인 2013년 창업자의 손자가 다시 문을 연 파란만장한 역사를 지니고 있다....서울관광재단은 중장년층은 과거를 회상하며 향수를 느끼고, 젊은 층들은 최근 뜨는 '레트로'(복고) 감성을... 폐업 후 8년 만인 2013년에 독수리다방 창업자의 손자가 재개업하면서 끊어졌던 명맥을 이었다. 옛 모습이...곳에서 창업하라" 3일 온라인 생중계로 진행된 '2020

In [ ]:
news_title_tfidf9 = tfidf.transform([news_title9])
news_title_predict9 = lr.predict(news_title_tfidf9)
news_title_predict9

array([1])

In [ ]:
news10=pd.read_csv('/content/네이버뉴스_서울_창업_20201001_20201031.csv',encoding='utf8')

In [ ]:
news10['title'] = news10['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title10=''
for i in range(len(news10.title)):
  news_title10=news_title10 + news10.iloc[i,2]+''

print(news_title10)

큰맘 먹고 시작한 창업이었지만 코로나19와 맞물려 임대료 납부가 어려워졌기 때문이다. 문제는 김 씨만의... 대규모 폐업과 더불어 서울교통공사가 GS리테일과 맺은 6·7호선 유휴공간 임대계약이 끝나가면서 텅 빈...1109개가 창업한 것으로 나타났다. 특히 전국 피트니스 센터 2곳 중 1곳은 서울과 경기도 등 수도권에... 코로나19 초기인 2~3월에 폐업한 피트니스 센터가 전년 대비 증가했지만 안정세를 나타낸 4~6월에는 폐업...지원 대상은 올해 6월 30일 이전 강남구 관내에서 창업한 연 매출 5억원 미만의 소상공인이다. 신청은... 다만 서울시 자영업자 생존자금 수령자, 사실상 휴·폐업 중인 사업장, 중소기업육성기금 융자지원 제한...소상공인의 폐업률이 증가하는 상황에서 창업을 준비하는 예비 창업자에게 중요한 정보가 될 것이라는 점에서 심사위원들에게 높은 평가를 받았다고 서울신보는 전했다. 우수상은 서강고등학교팀(서강대학교 경영학...안정적인 창업을 하는 것이 도움이 될 것으로 보인다. 이런 가운데 어려운 상황 속에서도 가맹점과의 상생경영으로 안정적인 매출을 올리고 있는 수제 돈까스 전문 '동명카츠'가 '동명카츠 서울천호점' 오픈 소식을...이에 대해 서울 종로구의 한 미샤 매장에서 근무하는 직원은 “대체적으로 온라인에서 크게 할인하는... 미샤 창업주인 서영필 에이블씨엔씨 회장은 2017년 사모펀드에 회사를 매각한 바 있다. “먹지마세요. 피부에...2013년에 가천대길병원, 경북대병원, 고대구로병원, 고대안암병원, 분당차병원, 삼성서울병원, 서울대병원... 폐업한 7개사를 제외한 연구중심병원 창업기업 총 74개사의 종업원수는 2019년 기준 509명이며, 경력이...이는 단순히 제조업 휴·폐업으로 그치지 않고, 기획한 제품을 생산할 공장이 필요한 브랜드 기업의 사업에도... 정 대표는 지난 29일 밀레니엄 힐튼 서울 호텔에서 진행된 시상식에서 “이번 아이디어 공모전에 지원하게...서울 마포구(구청장 유동균)는 소상공인 새희망자금 신청자들의 편의를 위

In [ ]:
news_title_tfidf10 = tfidf.transform([news_title10])
news_title_predict10 = lr.predict(news_title_tfidf10)
news_title_predict10

array([1])

In [ ]:
news11=pd.read_csv('/content/네이버뉴스_서울_창업_20201101_20201130.csv',encoding='utf8')

In [ ]:
news11['title'] = news11['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title11=''
for i in range(len(news11.title)):
  news_title11=news_title11 + news11.iloc[i,2]+''

print(news_title11)

지난 6개월 동안 서울지역에서 폐업한 사업장 수이다. 이 가운데 1년을 못 버틴 곳이 3138곳이고, 10년 이상... 코로나 시대 디지털 플랫폼을 활용해 소상공인의 적정 창업과 준비된 창업을 지원하는 정책 사업 사례도...감사하지만, 서울시장 출마 진지하고 신중하게 고민할 시간 필요 - 경제구조 변화 속에서 중기부 기반 만드는... 최근에 보니까 창업기업 동향이라는 게 있더라고요. 이게 사실은 코로나19 이후에 폐업이라든가 이런 것들이...전준우 기자,김진희 기자 = 서울시 내년도 예산안이 처음으로 40조원을 돌파했다. 올해보다 1.3%(5120억원)... 금융, 온라인 판로개척, 창업-성장-폐업에 대한 맞춤형 지원 등을 통해 지역상권 소비 환경을 조성한다....미용실이 가장 많이 밀집한 곳은 경기도(2만4453개)와 서울(1만8912개)이다. 최근 10년간 미용실은 증가세(약 28%)를 보였지만 코로나19사태로 신규 미용실 수가 감소세로 전환했다. 지난해 1월~9월까지 창업한 미용실은...서울세관 관계자는 "이번 사례는 특수관계인끼리 고의 폐업, 창업, 우회 수입을 반복한 상습 체납을 빅데이터 분석으로 밝혀내고 체납액 징수까지 성공한 경우"라고 설명했다. 서울세관은 "악덕 체납자의 은닉재산을...4000개)와 서울(1만 9000개), 인구대비 미용실 수로는 대구(1만명 당 26개)와 광주(1만명 당 25.4개)가 많은 것으로 나타났다. 코로나19에 따라 미용업 창업과 매출이 영향을 받은 반면, 폐업은 오히려 지난해보다...[성남=스포츠서울 좌승훈 기자]전국 최초로 ‘성남시 데이터거래소’가 구축된다. 30일 성남시에 따르면... 예비 창업자와 소상공인에게 지역·업종별 창·폐업, 인구, 집객시설 등 상권의 현황과 경쟁정도, 입지등급...사상 처음으로 40조원이 넘는 예산안을 편성한 서울시가 코로나 불황 극복과 민생경제 회복에... 청년 등에 대한 창업, 민간고용 등 간접 일자리 20만7051개 창출에는 3606억원을 편성했다. 주요 사업은 캠퍼스타운...휴·폐

In [ ]:
news_title_tfidf11 = tfidf.transform([news_title11])
news_title_predict11 = lr.predict(news_title_tfidf11)
news_title_predict11

array([1])

In [ ]:
news12=pd.read_csv('/content/네이버뉴스_서울_창업_20201201_20201231.csv',encoding='utf8')

In [ ]:
news12['title'] = news12['title'].apply(lambda x: re.sub(r'[^ ㄱ-ㅣ가-힣]+', "", x))
news_title12=''
for i in range(len(news12.title)):
  news_title12=news_title12 + news12.iloc[i,2]+''

print(news_title12)

이밖에도 결혼이민여성 중소기업 취업매칭, 청년창업의 활성화를 도모하였으며, 시니어들 및 폐업한 대표에게 재창업을 통한 회생의 기회를 제공하였다. 아울러, 채 본부장은 청년창업활성화를 위한 서울청년창업사...서울창업디딤터를 수탁 운영하고 있는 '광운대학교'는 광운대학교 80주년 기념관 대강당에서 '대학 주도의... 포럼 2부 행사에서는 청년창업가 특강으로 ㈜업드림코리아(이지웅 대표)가 참석하여 '아름다운 폐업을 꿈꾸는...서울창업디딤터를 수탁 운영하고 있는 ‘광운대학교’는 지난 2일 광운대학교 80주년 기념관 대강당에서... 포럼 2부 행사에서는 청년창업가 특강으로 ㈜업드림코리아(이지웅 대표)가 참석하여 &lt;“아름다운 폐업을 꿈꾸는...'치킨 전쟁'의 정도는 도시와 농촌으로도 구분해 볼 수 있는데요, 도시지역인 서울 마포구와 농촌 지역인... 신규 창업으로 이어졌습니다. 지역 간, 도-농간 자영업자들의 경쟁 상황, 어려움 등도 치킨집 휴폐업...서울에서 아파트값이 가장 많이 오른 곳은 구로구로 2.56%의 상승률을 기록했다. 그 뒤를 강북구(2.05%), 노원구(2.01%) 등이 이었다. 한 전문가는 “예전에는 은퇴 후 퇴직금과 주택 판 자금을 모아 창업 전선에 뛰어...폐업 부담 완화와 신속한 재기를 지원하는 '희망리턴패키지' 사업을 420억원에서 691억원으로 확대했다. 특히 업종전환·재창업 소상공인에게 필요한 사업화 비용 일부를 지원하는 예산 120억원도 신설했다. 마지막으로...많은 서울의 소형 상가 공실률은 2분기 4.2%에서 5.7%로 급증했다. 이 같은 올해 3분기 공실률은 관련 통계가 이뤄진 2014년 이후 최대 수치다.  지난달 소상공인연합회가 조사한 결과 소상공인 10명 중 7명이 폐업을 고민...그다음에 창업에 관련 도움을 찾기 위해서 또는 개인의 역량을 개발하여 사회참여를 위한 다양한 활동을 하기 위해서 저희를 찾아주셨는데요. 그중에 기억에 남는 사례로 결혼과 동시에 남편은 울산에 그리고 아내는 서울...경기도 일자리재단은 일자리 정보 

In [ ]:
news_title_tfidf12 = tfidf.transform([news_title12])
news_title_predict12 = lr.predict(news_title_tfidf12)
news_title_predict12

array([1])